// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: finances.sql

package finances

import (
	"context"
)

const getFinance = `-- name: GetFinance :one
SELECT id, account, balance FROM finances
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetFinance(ctx context.Context, id int64) (Finance, error) {
	row := q.db.QueryRowContext(ctx, getFinance, id)
	var i Finance
	err := row.Scan(&i.ID, &i.Account, &i.Balance)
	return i, err
}

const listFinances = `-- name: ListFinances :many
SELECT id, account, balance FROM finances
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListFinancesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListFinances(ctx context.Context, arg ListFinancesParams) ([]Finance, error) {
	rows, err := q.db.QueryContext(ctx, listFinances, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finance
	for rows.Next() {
		var i Finance
		if err := rows.Scan(&i.ID, &i.Account, &i.Balance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
