// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package finances

import (
	"database/sql"
)

type FinancialSummary struct {
	Account      string          `json:"account"`
	BalanceCents sql.NullFloat64 `json:"balance_cents"`
	Entries      int64           `json:"entries"`
}

type Ledger struct {
	ID          int64          `json:"id"`
	Account     string         `json:"account"`
	AmountCents int64          `json:"amount_cents"`
	Currency    string         `json:"currency"`
	Description sql.NullString `json:"description"`
	CreatedAt   string         `json:"created_at"`
}
