// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package finances

type Finance struct {
	ID      int64  `json:"id"`
	Account string `json:"account"`
	Balance int64  `json:"balance"`
}
