// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package finances

import (
	"context"
	"database/sql"
)

type Querier interface {
	GetAccountBalance(ctx context.Context, account string) (FinancialSummary, error)
	// schema: migrations/004_create_finances.sql
	GetLedgerEntry(ctx context.Context, id int64) (Ledger, error)
	// NOTE: ledger table used in production migration. The view `financial_summary` provides balances by account.
	InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) (Ledger, error)
	ListLedgerEntries(ctx context.Context, arg ListLedgerEntriesParams) ([]Ledger, error)
	ListLedgerForAccount(ctx context.Context, arg ListLedgerForAccountParams) ([]Ledger, error)
	SumLedgerBetweenDates(ctx context.Context, arg SumLedgerBetweenDatesParams) (sql.NullFloat64, error)
}

var _ Querier = (*Queries)(nil)
