// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package finances

import (
	"context"
)

type Querier interface {
	GetFinance(ctx context.Context, id int64) (Finance, error)
	ListFinances(ctx context.Context, arg ListFinancesParams) ([]Finance, error)
}

var _ Querier = (*Queries)(nil)
