// Code generated by MockGen. DO NOT EDIT.
// Source: internal/store/configs/querier.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	configs "github.com/garnizeh/luckyfive/internal/store/configs"
	gomock "github.com/golang/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// DeleteConfig mocks base method.
func (m *MockQuerier) DeleteConfig(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteConfig", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteConfig indicates an expected call of DeleteConfig.
func (mr *MockQuerierMockRecorder) DeleteConfig(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConfig", reflect.TypeOf((*MockQuerier)(nil).DeleteConfig), ctx, id)
}

// GetConfig mocks base method.
func (m *MockQuerier) GetConfig(ctx context.Context, id int64) (configs.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig", ctx, id)
	ret0, _ := ret[0].(configs.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockQuerierMockRecorder) GetConfig(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockQuerier)(nil).GetConfig), ctx, id)
}

// GetConfigByName mocks base method.
func (m *MockQuerier) GetConfigByName(ctx context.Context, name string) (configs.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigByName", ctx, name)
	ret0, _ := ret[0].(configs.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigByName indicates an expected call of GetConfigByName.
func (mr *MockQuerierMockRecorder) GetConfigByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigByName", reflect.TypeOf((*MockQuerier)(nil).GetConfigByName), ctx, name)
}

// GetConfigPresetByName mocks base method.
func (m *MockQuerier) GetConfigPresetByName(ctx context.Context, name string) (configs.ConfigPreset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigPresetByName", ctx, name)
	ret0, _ := ret[0].(configs.ConfigPreset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigPresetByName indicates an expected call of GetConfigPresetByName.
func (mr *MockQuerierMockRecorder) GetConfigPresetByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigPresetByName", reflect.TypeOf((*MockQuerier)(nil).GetConfigPresetByName), ctx, name)
}

// GetConfigPresets mocks base method.
func (m *MockQuerier) GetConfigPresets(ctx context.Context) ([]configs.ConfigPreset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigPresets", ctx)
	ret0, _ := ret[0].([]configs.ConfigPreset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigPresets indicates an expected call of GetConfigPresets.
func (mr *MockQuerierMockRecorder) GetConfigPresets(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigPresets", reflect.TypeOf((*MockQuerier)(nil).GetConfigPresets), ctx)
}

// GetDefaultConfigForMode mocks base method.
func (m *MockQuerier) GetDefaultConfigForMode(ctx context.Context, mode string) (configs.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultConfigForMode", ctx, mode)
	ret0, _ := ret[0].(configs.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDefaultConfigForMode indicates an expected call of GetDefaultConfigForMode.
func (mr *MockQuerierMockRecorder) GetDefaultConfigForMode(ctx, mode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultConfigForMode", reflect.TypeOf((*MockQuerier)(nil).GetDefaultConfigForMode), ctx, mode)
}

// InsertConfig mocks base method.
func (m *MockQuerier) InsertConfig(ctx context.Context, arg configs.InsertConfigParams) (configs.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertConfig", ctx, arg)
	ret0, _ := ret[0].(configs.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertConfig indicates an expected call of InsertConfig.
func (mr *MockQuerierMockRecorder) InsertConfig(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertConfig", reflect.TypeOf((*MockQuerier)(nil).InsertConfig), ctx, arg)
}

// ListConfigs mocks base method.
func (m *MockQuerier) ListConfigs(ctx context.Context, arg configs.ListConfigsParams) ([]configs.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConfigs", ctx, arg)
	ret0, _ := ret[0].([]configs.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConfigs indicates an expected call of ListConfigs.
func (mr *MockQuerierMockRecorder) ListConfigs(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConfigs", reflect.TypeOf((*MockQuerier)(nil).ListConfigs), ctx, arg)
}

// ListConfigsByMode mocks base method.
func (m *MockQuerier) ListConfigsByMode(ctx context.Context, arg configs.ListConfigsByModeParams) ([]configs.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConfigsByMode", ctx, arg)
	ret0, _ := ret[0].([]configs.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConfigsByMode indicates an expected call of ListConfigsByMode.
func (mr *MockQuerierMockRecorder) ListConfigsByMode(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConfigsByMode", reflect.TypeOf((*MockQuerier)(nil).ListConfigsByMode), ctx, arg)
}

// SetConfigAsDefault mocks base method.
func (m *MockQuerier) SetConfigAsDefault(ctx context.Context, arg configs.SetConfigAsDefaultParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetConfigAsDefault", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetConfigAsDefault indicates an expected call of SetConfigAsDefault.
func (mr *MockQuerierMockRecorder) SetConfigAsDefault(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetConfigAsDefault", reflect.TypeOf((*MockQuerier)(nil).SetConfigAsDefault), ctx, arg)
}

// UpdateConfig mocks base method.
func (m *MockQuerier) UpdateConfig(ctx context.Context, arg configs.UpdateConfigParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConfig", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateConfig indicates an expected call of UpdateConfig.
func (mr *MockQuerierMockRecorder) UpdateConfig(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConfig", reflect.TypeOf((*MockQuerier)(nil).UpdateConfig), ctx, arg)
}
