// Code generated by MockGen. DO NOT EDIT.
// Source: internal/store/configs/querier.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	configs "github.com/garnizeh/luckyfive/internal/store/configs"
	gomock "github.com/golang/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// CreateConfig mocks base method.
func (m *MockQuerier) CreateConfig(ctx context.Context, arg configs.CreateConfigParams) (configs.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateConfig", ctx, arg)
	ret0, _ := ret[0].(configs.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateConfig indicates an expected call of CreateConfig.
func (mr *MockQuerierMockRecorder) CreateConfig(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateConfig", reflect.TypeOf((*MockQuerier)(nil).CreateConfig), ctx, arg)
}

// DeleteConfig mocks base method.
func (m *MockQuerier) DeleteConfig(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteConfig", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteConfig indicates an expected call of DeleteConfig.
func (mr *MockQuerierMockRecorder) DeleteConfig(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConfig", reflect.TypeOf((*MockQuerier)(nil).DeleteConfig), ctx, id)
}

// GetConfig mocks base method.
func (m *MockQuerier) GetConfig(ctx context.Context, id int64) (configs.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig", ctx, id)
	ret0, _ := ret[0].(configs.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockQuerierMockRecorder) GetConfig(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockQuerier)(nil).GetConfig), ctx, id)
}

// GetConfigByName mocks base method.
func (m *MockQuerier) GetConfigByName(ctx context.Context, name string) (configs.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigByName", ctx, name)
	ret0, _ := ret[0].(configs.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigByName indicates an expected call of GetConfigByName.
func (mr *MockQuerierMockRecorder) GetConfigByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigByName", reflect.TypeOf((*MockQuerier)(nil).GetConfigByName), ctx, name)
}

// GetDefaultConfig mocks base method.
func (m *MockQuerier) GetDefaultConfig(ctx context.Context, mode string) (configs.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultConfig", ctx, mode)
	ret0, _ := ret[0].(configs.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDefaultConfig indicates an expected call of GetDefaultConfig.
func (mr *MockQuerierMockRecorder) GetDefaultConfig(ctx, mode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultConfig", reflect.TypeOf((*MockQuerier)(nil).GetDefaultConfig), ctx, mode)
}

// GetPreset mocks base method.
func (m *MockQuerier) GetPreset(ctx context.Context, name string) (configs.ConfigPreset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPreset", ctx, name)
	ret0, _ := ret[0].(configs.ConfigPreset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPreset indicates an expected call of GetPreset.
func (mr *MockQuerierMockRecorder) GetPreset(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPreset", reflect.TypeOf((*MockQuerier)(nil).GetPreset), ctx, name)
}

// IncrementConfigUsage mocks base method.
func (m *MockQuerier) IncrementConfigUsage(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementConfigUsage", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementConfigUsage indicates an expected call of IncrementConfigUsage.
func (mr *MockQuerierMockRecorder) IncrementConfigUsage(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementConfigUsage", reflect.TypeOf((*MockQuerier)(nil).IncrementConfigUsage), ctx, id)
}

// ListConfigs mocks base method.
func (m *MockQuerier) ListConfigs(ctx context.Context, arg configs.ListConfigsParams) ([]configs.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConfigs", ctx, arg)
	ret0, _ := ret[0].([]configs.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConfigs indicates an expected call of ListConfigs.
func (mr *MockQuerierMockRecorder) ListConfigs(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConfigs", reflect.TypeOf((*MockQuerier)(nil).ListConfigs), ctx, arg)
}

// ListConfigsByMode mocks base method.
func (m *MockQuerier) ListConfigsByMode(ctx context.Context, arg configs.ListConfigsByModeParams) ([]configs.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConfigsByMode", ctx, arg)
	ret0, _ := ret[0].([]configs.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConfigsByMode indicates an expected call of ListConfigsByMode.
func (mr *MockQuerierMockRecorder) ListConfigsByMode(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConfigsByMode", reflect.TypeOf((*MockQuerier)(nil).ListConfigsByMode), ctx, arg)
}

// ListPresets mocks base method.
func (m *MockQuerier) ListPresets(ctx context.Context) ([]configs.ConfigPreset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPresets", ctx)
	ret0, _ := ret[0].([]configs.ConfigPreset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPresets indicates an expected call of ListPresets.
func (mr *MockQuerierMockRecorder) ListPresets(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPresets", reflect.TypeOf((*MockQuerier)(nil).ListPresets), ctx)
}

// SetDefaultConfig mocks base method.
func (m *MockQuerier) SetDefaultConfig(ctx context.Context, arg configs.SetDefaultConfigParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDefaultConfig", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDefaultConfig indicates an expected call of SetDefaultConfig.
func (mr *MockQuerierMockRecorder) SetDefaultConfig(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDefaultConfig", reflect.TypeOf((*MockQuerier)(nil).SetDefaultConfig), ctx, arg)
}

// UpdateConfig mocks base method.
func (m *MockQuerier) UpdateConfig(ctx context.Context, arg configs.UpdateConfigParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConfig", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateConfig indicates an expected call of UpdateConfig.
func (mr *MockQuerierMockRecorder) UpdateConfig(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConfig", reflect.TypeOf((*MockQuerier)(nil).UpdateConfig), ctx, arg)
}
