// Code generated by MockGen. DO NOT EDIT.
// Source: internal/store/configs/querier.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	configs "github.com/garnizeh/luckyfive/internal/store/configs"
	gomock "github.com/golang/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// GetConfig mocks base method.
func (m *MockQuerier) GetConfig(ctx context.Context, id int64) (configs.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig", ctx, id)
	ret0, _ := ret[0].(configs.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockQuerierMockRecorder) GetConfig(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockQuerier)(nil).GetConfig), ctx, id)
}

// GetConfigByKey mocks base method.
func (m *MockQuerier) GetConfigByKey(ctx context.Context, key string) (configs.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigByKey", ctx, key)
	ret0, _ := ret[0].(configs.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigByKey indicates an expected call of GetConfigByKey.
func (mr *MockQuerierMockRecorder) GetConfigByKey(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigByKey", reflect.TypeOf((*MockQuerier)(nil).GetConfigByKey), ctx, key)
}

// GetDefaultPresetForMode mocks base method.
func (m *MockQuerier) GetDefaultPresetForMode(ctx context.Context, mode string) (configs.ConfigPreset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultPresetForMode", ctx, mode)
	ret0, _ := ret[0].(configs.ConfigPreset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDefaultPresetForMode indicates an expected call of GetDefaultPresetForMode.
func (mr *MockQuerierMockRecorder) GetDefaultPresetForMode(ctx, mode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultPresetForMode", reflect.TypeOf((*MockQuerier)(nil).GetDefaultPresetForMode), ctx, mode)
}

// InsertConfig mocks base method.
func (m *MockQuerier) InsertConfig(ctx context.Context, arg configs.InsertConfigParams) (configs.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertConfig", ctx, arg)
	ret0, _ := ret[0].(configs.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertConfig indicates an expected call of InsertConfig.
func (mr *MockQuerierMockRecorder) InsertConfig(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertConfig", reflect.TypeOf((*MockQuerier)(nil).InsertConfig), ctx, arg)
}

// InsertPreset mocks base method.
func (m *MockQuerier) InsertPreset(ctx context.Context, arg configs.InsertPresetParams) (configs.ConfigPreset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertPreset", ctx, arg)
	ret0, _ := ret[0].(configs.ConfigPreset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertPreset indicates an expected call of InsertPreset.
func (mr *MockQuerierMockRecorder) InsertPreset(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertPreset", reflect.TypeOf((*MockQuerier)(nil).InsertPreset), ctx, arg)
}

// ListConfigs mocks base method.
func (m *MockQuerier) ListConfigs(ctx context.Context, arg configs.ListConfigsParams) ([]configs.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConfigs", ctx, arg)
	ret0, _ := ret[0].([]configs.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConfigs indicates an expected call of ListConfigs.
func (mr *MockQuerierMockRecorder) ListConfigs(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConfigs", reflect.TypeOf((*MockQuerier)(nil).ListConfigs), ctx, arg)
}

// ListPresetsByMode mocks base method.
func (m *MockQuerier) ListPresetsByMode(ctx context.Context, arg configs.ListPresetsByModeParams) ([]configs.ConfigPreset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPresetsByMode", ctx, arg)
	ret0, _ := ret[0].([]configs.ConfigPreset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPresetsByMode indicates an expected call of ListPresetsByMode.
func (mr *MockQuerierMockRecorder) ListPresetsByMode(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPresetsByMode", reflect.TypeOf((*MockQuerier)(nil).ListPresetsByMode), ctx, arg)
}

// UpdateConfig mocks base method.
func (m *MockQuerier) UpdateConfig(ctx context.Context, arg configs.UpdateConfigParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConfig", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateConfig indicates an expected call of UpdateConfig.
func (mr *MockQuerierMockRecorder) UpdateConfig(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConfig", reflect.TypeOf((*MockQuerier)(nil).UpdateConfig), ctx, arg)
}
