// Code generated by MockGen. DO NOT EDIT.
// Source: internal/store/simulations/querier.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	simulations "github.com/garnizeh/luckyfive/internal/store/simulations"
	gomock "github.com/golang/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// CancelSimulation mocks base method.
func (m *MockQuerier) CancelSimulation(ctx context.Context, arg simulations.CancelSimulationParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelSimulation", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelSimulation indicates an expected call of CancelSimulation.
func (mr *MockQuerierMockRecorder) CancelSimulation(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelSimulation", reflect.TypeOf((*MockQuerier)(nil).CancelSimulation), ctx, arg)
}

// ClaimPendingSimulation mocks base method.
func (m *MockQuerier) ClaimPendingSimulation(ctx context.Context, arg simulations.ClaimPendingSimulationParams) (simulations.Simulation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimPendingSimulation", ctx, arg)
	ret0, _ := ret[0].(simulations.Simulation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimPendingSimulation indicates an expected call of ClaimPendingSimulation.
func (mr *MockQuerierMockRecorder) ClaimPendingSimulation(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimPendingSimulation", reflect.TypeOf((*MockQuerier)(nil).ClaimPendingSimulation), ctx, arg)
}

// CompleteSimulation mocks base method.
func (m *MockQuerier) CompleteSimulation(ctx context.Context, arg simulations.CompleteSimulationParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteSimulation", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteSimulation indicates an expected call of CompleteSimulation.
func (mr *MockQuerierMockRecorder) CompleteSimulation(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteSimulation", reflect.TypeOf((*MockQuerier)(nil).CompleteSimulation), ctx, arg)
}

// CountSimulationsByStatus mocks base method.
func (m *MockQuerier) CountSimulationsByStatus(ctx context.Context, status string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountSimulationsByStatus", ctx, status)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountSimulationsByStatus indicates an expected call of CountSimulationsByStatus.
func (mr *MockQuerierMockRecorder) CountSimulationsByStatus(ctx, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountSimulationsByStatus", reflect.TypeOf((*MockQuerier)(nil).CountSimulationsByStatus), ctx, status)
}

// CreateSimulation mocks base method.
func (m *MockQuerier) CreateSimulation(ctx context.Context, arg simulations.CreateSimulationParams) (simulations.Simulation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSimulation", ctx, arg)
	ret0, _ := ret[0].(simulations.Simulation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSimulation indicates an expected call of CreateSimulation.
func (mr *MockQuerierMockRecorder) CreateSimulation(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSimulation", reflect.TypeOf((*MockQuerier)(nil).CreateSimulation), ctx, arg)
}

// FailSimulation mocks base method.
func (m *MockQuerier) FailSimulation(ctx context.Context, arg simulations.FailSimulationParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FailSimulation", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// FailSimulation indicates an expected call of FailSimulation.
func (mr *MockQuerierMockRecorder) FailSimulation(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FailSimulation", reflect.TypeOf((*MockQuerier)(nil).FailSimulation), ctx, arg)
}

// GetContestResults mocks base method.
func (m *MockQuerier) GetContestResults(ctx context.Context, arg simulations.GetContestResultsParams) ([]simulations.SimulationContestResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContestResults", ctx, arg)
	ret0, _ := ret[0].([]simulations.SimulationContestResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContestResults indicates an expected call of GetContestResults.
func (mr *MockQuerierMockRecorder) GetContestResults(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContestResults", reflect.TypeOf((*MockQuerier)(nil).GetContestResults), ctx, arg)
}

// GetContestResultsByMinHits mocks base method.
func (m *MockQuerier) GetContestResultsByMinHits(ctx context.Context, arg simulations.GetContestResultsByMinHitsParams) ([]simulations.SimulationContestResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContestResultsByMinHits", ctx, arg)
	ret0, _ := ret[0].([]simulations.SimulationContestResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContestResultsByMinHits indicates an expected call of GetContestResultsByMinHits.
func (mr *MockQuerierMockRecorder) GetContestResultsByMinHits(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContestResultsByMinHits", reflect.TypeOf((*MockQuerier)(nil).GetContestResultsByMinHits), ctx, arg)
}

// GetSimulation mocks base method.
func (m *MockQuerier) GetSimulation(ctx context.Context, id int64) (simulations.Simulation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSimulation", ctx, id)
	ret0, _ := ret[0].(simulations.Simulation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSimulation indicates an expected call of GetSimulation.
func (mr *MockQuerierMockRecorder) GetSimulation(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSimulation", reflect.TypeOf((*MockQuerier)(nil).GetSimulation), ctx, id)
}

// InsertContestResult mocks base method.
func (m *MockQuerier) InsertContestResult(ctx context.Context, arg simulations.InsertContestResultParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertContestResult", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertContestResult indicates an expected call of InsertContestResult.
func (mr *MockQuerierMockRecorder) InsertContestResult(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertContestResult", reflect.TypeOf((*MockQuerier)(nil).InsertContestResult), ctx, arg)
}

// ListSimulations mocks base method.
func (m *MockQuerier) ListSimulations(ctx context.Context, arg simulations.ListSimulationsParams) ([]simulations.Simulation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSimulations", ctx, arg)
	ret0, _ := ret[0].([]simulations.Simulation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSimulations indicates an expected call of ListSimulations.
func (mr *MockQuerierMockRecorder) ListSimulations(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSimulations", reflect.TypeOf((*MockQuerier)(nil).ListSimulations), ctx, arg)
}

// ListSimulationsByStatus mocks base method.
func (m *MockQuerier) ListSimulationsByStatus(ctx context.Context, arg simulations.ListSimulationsByStatusParams) ([]simulations.Simulation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSimulationsByStatus", ctx, arg)
	ret0, _ := ret[0].([]simulations.Simulation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSimulationsByStatus indicates an expected call of ListSimulationsByStatus.
func (mr *MockQuerierMockRecorder) ListSimulationsByStatus(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSimulationsByStatus", reflect.TypeOf((*MockQuerier)(nil).ListSimulationsByStatus), ctx, arg)
}

// UpdateSimulationStatus mocks base method.
func (m *MockQuerier) UpdateSimulationStatus(ctx context.Context, arg simulations.UpdateSimulationStatusParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSimulationStatus", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSimulationStatus indicates an expected call of UpdateSimulationStatus.
func (mr *MockQuerierMockRecorder) UpdateSimulationStatus(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSimulationStatus", reflect.TypeOf((*MockQuerier)(nil).UpdateSimulationStatus), ctx, arg)
}
