// Code generated by MockGen. DO NOT EDIT.
// Source: internal/store/simulations/querier.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	simulations "github.com/garnizeh/luckyfive/internal/store/simulations"
	gomock "github.com/golang/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// CreateAnalysisJob mocks base method.
func (m *MockQuerier) CreateAnalysisJob(ctx context.Context, arg simulations.CreateAnalysisJobParams) (simulations.AnalysisJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAnalysisJob", ctx, arg)
	ret0, _ := ret[0].(simulations.AnalysisJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAnalysisJob indicates an expected call of CreateAnalysisJob.
func (mr *MockQuerierMockRecorder) CreateAnalysisJob(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAnalysisJob", reflect.TypeOf((*MockQuerier)(nil).CreateAnalysisJob), ctx, arg)
}

// DeleteSimulation mocks base method.
func (m *MockQuerier) DeleteSimulation(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSimulation", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSimulation indicates an expected call of DeleteSimulation.
func (mr *MockQuerierMockRecorder) DeleteSimulation(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSimulation", reflect.TypeOf((*MockQuerier)(nil).DeleteSimulation), ctx, id)
}

// GetSimulation mocks base method.
func (m *MockQuerier) GetSimulation(ctx context.Context, id int64) (simulations.Simulation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSimulation", ctx, id)
	ret0, _ := ret[0].(simulations.Simulation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSimulation indicates an expected call of GetSimulation.
func (mr *MockQuerierMockRecorder) GetSimulation(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSimulation", reflect.TypeOf((*MockQuerier)(nil).GetSimulation), ctx, id)
}

// InsertSimulation mocks base method.
func (m *MockQuerier) InsertSimulation(ctx context.Context, arg simulations.InsertSimulationParams) (simulations.Simulation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertSimulation", ctx, arg)
	ret0, _ := ret[0].(simulations.Simulation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertSimulation indicates an expected call of InsertSimulation.
func (mr *MockQuerierMockRecorder) InsertSimulation(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertSimulation", reflect.TypeOf((*MockQuerier)(nil).InsertSimulation), ctx, arg)
}

// InsertSimulationResult mocks base method.
func (m *MockQuerier) InsertSimulationResult(ctx context.Context, arg simulations.InsertSimulationResultParams) (simulations.SimulationContestResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertSimulationResult", ctx, arg)
	ret0, _ := ret[0].(simulations.SimulationContestResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertSimulationResult indicates an expected call of InsertSimulationResult.
func (mr *MockQuerierMockRecorder) InsertSimulationResult(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertSimulationResult", reflect.TypeOf((*MockQuerier)(nil).InsertSimulationResult), ctx, arg)
}

// ListAnalysisJobsBySimulation mocks base method.
func (m *MockQuerier) ListAnalysisJobsBySimulation(ctx context.Context, arg simulations.ListAnalysisJobsBySimulationParams) ([]simulations.AnalysisJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAnalysisJobsBySimulation", ctx, arg)
	ret0, _ := ret[0].([]simulations.AnalysisJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAnalysisJobsBySimulation indicates an expected call of ListAnalysisJobsBySimulation.
func (mr *MockQuerierMockRecorder) ListAnalysisJobsBySimulation(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAnalysisJobsBySimulation", reflect.TypeOf((*MockQuerier)(nil).ListAnalysisJobsBySimulation), ctx, arg)
}

// ListSimulationResults mocks base method.
func (m *MockQuerier) ListSimulationResults(ctx context.Context, arg simulations.ListSimulationResultsParams) ([]simulations.SimulationContestResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSimulationResults", ctx, arg)
	ret0, _ := ret[0].([]simulations.SimulationContestResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSimulationResults indicates an expected call of ListSimulationResults.
func (mr *MockQuerierMockRecorder) ListSimulationResults(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSimulationResults", reflect.TypeOf((*MockQuerier)(nil).ListSimulationResults), ctx, arg)
}

// ListSimulations mocks base method.
func (m *MockQuerier) ListSimulations(ctx context.Context, arg simulations.ListSimulationsParams) ([]simulations.Simulation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSimulations", ctx, arg)
	ret0, _ := ret[0].([]simulations.Simulation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSimulations indicates an expected call of ListSimulations.
func (mr *MockQuerierMockRecorder) ListSimulations(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSimulations", reflect.TypeOf((*MockQuerier)(nil).ListSimulations), ctx, arg)
}

// UpdateSimulation mocks base method.
func (m *MockQuerier) UpdateSimulation(ctx context.Context, arg simulations.UpdateSimulationParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSimulation", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSimulation indicates an expected call of UpdateSimulation.
func (mr *MockQuerierMockRecorder) UpdateSimulation(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSimulation", reflect.TypeOf((*MockQuerier)(nil).UpdateSimulation), ctx, arg)
}
