// Code generated by MockGen. DO NOT EDIT.
// Source: internal/store/finances/querier.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	finances "github.com/garnizeh/luckyfive/internal/store/finances"
	gomock "github.com/golang/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// GetAccountBalance mocks base method.
func (m *MockQuerier) GetAccountBalance(ctx context.Context, account string) (finances.FinancialSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountBalance", ctx, account)
	ret0, _ := ret[0].(finances.FinancialSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountBalance indicates an expected call of GetAccountBalance.
func (mr *MockQuerierMockRecorder) GetAccountBalance(ctx, account interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountBalance", reflect.TypeOf((*MockQuerier)(nil).GetAccountBalance), ctx, account)
}

// GetLedgerEntry mocks base method.
func (m *MockQuerier) GetLedgerEntry(ctx context.Context, id int64) (finances.Ledger, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLedgerEntry", ctx, id)
	ret0, _ := ret[0].(finances.Ledger)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLedgerEntry indicates an expected call of GetLedgerEntry.
func (mr *MockQuerierMockRecorder) GetLedgerEntry(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLedgerEntry", reflect.TypeOf((*MockQuerier)(nil).GetLedgerEntry), ctx, id)
}

// InsertLedgerEntry mocks base method.
func (m *MockQuerier) InsertLedgerEntry(ctx context.Context, arg finances.InsertLedgerEntryParams) (finances.Ledger, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertLedgerEntry", ctx, arg)
	ret0, _ := ret[0].(finances.Ledger)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertLedgerEntry indicates an expected call of InsertLedgerEntry.
func (mr *MockQuerierMockRecorder) InsertLedgerEntry(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertLedgerEntry", reflect.TypeOf((*MockQuerier)(nil).InsertLedgerEntry), ctx, arg)
}

// ListLedgerEntries mocks base method.
func (m *MockQuerier) ListLedgerEntries(ctx context.Context, arg finances.ListLedgerEntriesParams) ([]finances.Ledger, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLedgerEntries", ctx, arg)
	ret0, _ := ret[0].([]finances.Ledger)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLedgerEntries indicates an expected call of ListLedgerEntries.
func (mr *MockQuerierMockRecorder) ListLedgerEntries(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLedgerEntries", reflect.TypeOf((*MockQuerier)(nil).ListLedgerEntries), ctx, arg)
}

// ListLedgerForAccount mocks base method.
func (m *MockQuerier) ListLedgerForAccount(ctx context.Context, arg finances.ListLedgerForAccountParams) ([]finances.Ledger, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLedgerForAccount", ctx, arg)
	ret0, _ := ret[0].([]finances.Ledger)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLedgerForAccount indicates an expected call of ListLedgerForAccount.
func (mr *MockQuerierMockRecorder) ListLedgerForAccount(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLedgerForAccount", reflect.TypeOf((*MockQuerier)(nil).ListLedgerForAccount), ctx, arg)
}

// SumLedgerBetweenDates mocks base method.
func (m *MockQuerier) SumLedgerBetweenDates(ctx context.Context, arg finances.SumLedgerBetweenDatesParams) (sql.NullFloat64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SumLedgerBetweenDates", ctx, arg)
	ret0, _ := ret[0].(sql.NullFloat64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SumLedgerBetweenDates indicates an expected call of SumLedgerBetweenDates.
func (mr *MockQuerierMockRecorder) SumLedgerBetweenDates(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SumLedgerBetweenDates", reflect.TypeOf((*MockQuerier)(nil).SumLedgerBetweenDates), ctx, arg)
}
