// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sweeps

import (
	"database/sql"
)

type Sweep struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ConfigJson  string         `json:"config_json"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
	CreatedBy   sql.NullString `json:"created_by"`
	TimesUsed   sql.NullInt64  `json:"times_used"`
	LastUsedAt  sql.NullString `json:"last_used_at"`
}
