// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sweeps

import (
	"context"
)

type Querier interface {
	CreateSweep(ctx context.Context, arg CreateSweepParams) (Sweep, error)
	DeleteSweep(ctx context.Context, id int64) error
	GetSweep(ctx context.Context, id int64) (Sweep, error)
	GetSweepByName(ctx context.Context, name string) (Sweep, error)
	IncrementSweepUsage(ctx context.Context, id int64) error
	ListSweeps(ctx context.Context, arg ListSweepsParams) ([]Sweep, error)
	UpdateSweep(ctx context.Context, arg UpdateSweepParams) error
}

var _ Querier = (*Queries)(nil)
