// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sweeps.sql

package sweeps

import (
	"context"
	"database/sql"
)

const createSweep = `-- name: CreateSweep :one
INSERT INTO sweeps (
    name, description, config_json, created_by
) VALUES (?, ?, ?, ?)
RETURNING id, name, description, config_json, created_at, updated_at, created_by, times_used, last_used_at
`

type CreateSweepParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ConfigJson  string         `json:"config_json"`
	CreatedBy   sql.NullString `json:"created_by"`
}

func (q *Queries) CreateSweep(ctx context.Context, arg CreateSweepParams) (Sweep, error) {
	row := q.db.QueryRowContext(ctx, createSweep,
		arg.Name,
		arg.Description,
		arg.ConfigJson,
		arg.CreatedBy,
	)
	var i Sweep
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ConfigJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.TimesUsed,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteSweep = `-- name: DeleteSweep :exec
DELETE FROM sweeps
WHERE id = ?
`

func (q *Queries) DeleteSweep(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSweep, id)
	return err
}

const getSweep = `-- name: GetSweep :one
SELECT id, name, description, config_json, created_at, updated_at, created_by, times_used, last_used_at FROM sweeps
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetSweep(ctx context.Context, id int64) (Sweep, error) {
	row := q.db.QueryRowContext(ctx, getSweep, id)
	var i Sweep
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ConfigJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.TimesUsed,
		&i.LastUsedAt,
	)
	return i, err
}

const getSweepByName = `-- name: GetSweepByName :one
SELECT id, name, description, config_json, created_at, updated_at, created_by, times_used, last_used_at FROM sweeps
WHERE name = ?
LIMIT 1
`

func (q *Queries) GetSweepByName(ctx context.Context, name string) (Sweep, error) {
	row := q.db.QueryRowContext(ctx, getSweepByName, name)
	var i Sweep
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ConfigJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.TimesUsed,
		&i.LastUsedAt,
	)
	return i, err
}

const incrementSweepUsage = `-- name: IncrementSweepUsage :exec
UPDATE sweeps
SET times_used = times_used + 1,
    last_used_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) IncrementSweepUsage(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, incrementSweepUsage, id)
	return err
}

const listSweeps = `-- name: ListSweeps :many
SELECT id, name, description, config_json, created_at, updated_at, created_by, times_used, last_used_at FROM sweeps
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListSweepsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListSweeps(ctx context.Context, arg ListSweepsParams) ([]Sweep, error) {
	rows, err := q.db.QueryContext(ctx, listSweeps, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sweep
	for rows.Next() {
		var i Sweep
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ConfigJson,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.TimesUsed,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSweep = `-- name: UpdateSweep :exec
UPDATE sweeps
SET name = ?,
    description = ?,
    config_json = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateSweepParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ConfigJson  string         `json:"config_json"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateSweep(ctx context.Context, arg UpdateSweepParams) error {
	_, err := q.db.ExecContext(ctx, updateSweep,
		arg.Name,
		arg.Description,
		arg.ConfigJson,
		arg.ID,
	)
	return err
}
