// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sweep_execution

import (
	"context"
)

type Querier interface {
	CreateComparison(ctx context.Context, arg CreateComparisonParams) (Comparison, error)
	CreateSweepJob(ctx context.Context, arg CreateSweepJobParams) (SweepJob, error)
	CreateSweepSimulation(ctx context.Context, arg CreateSweepSimulationParams) error
	FinishSweepJob(ctx context.Context, arg FinishSweepJobParams) error
	GetComparison(ctx context.Context, id int64) (Comparison, error)
	GetComparisonMetrics(ctx context.Context, comparisonID int64) ([]ComparisonMetric, error)
	GetSweepJob(ctx context.Context, id int64) (SweepJob, error)
	GetSweepSimulationDetails(ctx context.Context, sweepJobID int64) ([]GetSweepSimulationDetailsRow, error)
	GetSweepSimulations(ctx context.Context, sweepJobID int64) ([]SweepSimulation, error)
	InsertComparisonMetric(ctx context.Context, arg InsertComparisonMetricParams) error
	ListSweepJobs(ctx context.Context, arg ListSweepJobsParams) ([]SweepJob, error)
	UpdateComparisonResult(ctx context.Context, arg UpdateComparisonResultParams) error
	UpdateSweepJobProgress(ctx context.Context, arg UpdateSweepJobProgressParams) error
}

var _ Querier = (*Queries)(nil)
