// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sweep_execution.sql

package sweep_execution

import (
	"context"
	"database/sql"
)

const createComparison = `-- name: CreateComparison :one
INSERT INTO comparisons (
    name, description, simulation_ids, metric
) VALUES (?, ?, ?, ?)
RETURNING id, name, description, simulation_ids, metric, created_at, result_json
`

type CreateComparisonParams struct {
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	SimulationIds string         `json:"simulation_ids"`
	Metric        string         `json:"metric"`
}

func (q *Queries) CreateComparison(ctx context.Context, arg CreateComparisonParams) (Comparison, error) {
	row := q.db.QueryRowContext(ctx, createComparison,
		arg.Name,
		arg.Description,
		arg.SimulationIds,
		arg.Metric,
	)
	var i Comparison
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SimulationIds,
		&i.Metric,
		&i.CreatedAt,
		&i.ResultJson,
	)
	return i, err
}

const createSweepJob = `-- name: CreateSweepJob :one
INSERT INTO sweep_jobs (
    name, description, sweep_config_json, base_contest_range,
    total_combinations, created_by
) VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, name, description, sweep_config_json, base_contest_range, status, total_combinations, completed_simulations, failed_simulations, created_at, started_at, finished_at, run_duration_ms, created_by
`

type CreateSweepJobParams struct {
	Name              string         `json:"name"`
	Description       sql.NullString `json:"description"`
	SweepConfigJson   string         `json:"sweep_config_json"`
	BaseContestRange  string         `json:"base_contest_range"`
	TotalCombinations int64          `json:"total_combinations"`
	CreatedBy         sql.NullString `json:"created_by"`
}

func (q *Queries) CreateSweepJob(ctx context.Context, arg CreateSweepJobParams) (SweepJob, error) {
	row := q.db.QueryRowContext(ctx, createSweepJob,
		arg.Name,
		arg.Description,
		arg.SweepConfigJson,
		arg.BaseContestRange,
		arg.TotalCombinations,
		arg.CreatedBy,
	)
	var i SweepJob
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SweepConfigJson,
		&i.BaseContestRange,
		&i.Status,
		&i.TotalCombinations,
		&i.CompletedSimulations,
		&i.FailedSimulations,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.RunDurationMs,
		&i.CreatedBy,
	)
	return i, err
}

const createSweepSimulation = `-- name: CreateSweepSimulation :exec
INSERT INTO sweep_simulations (
    sweep_job_id, simulation_id, variation_index, variation_params
) VALUES (?, ?, ?, ?)
`

type CreateSweepSimulationParams struct {
	SweepJobID      int64  `json:"sweep_job_id"`
	SimulationID    int64  `json:"simulation_id"`
	VariationIndex  int64  `json:"variation_index"`
	VariationParams string `json:"variation_params"`
}

func (q *Queries) CreateSweepSimulation(ctx context.Context, arg CreateSweepSimulationParams) error {
	_, err := q.db.ExecContext(ctx, createSweepSimulation,
		arg.SweepJobID,
		arg.SimulationID,
		arg.VariationIndex,
		arg.VariationParams,
	)
	return err
}

const finishSweepJob = `-- name: FinishSweepJob :exec
UPDATE sweep_jobs
SET status = ?,
    finished_at = ?,
    run_duration_ms = ?
WHERE id = ?
`

type FinishSweepJobParams struct {
	Status        string         `json:"status"`
	FinishedAt    sql.NullString `json:"finished_at"`
	RunDurationMs sql.NullInt64  `json:"run_duration_ms"`
	ID            int64          `json:"id"`
}

func (q *Queries) FinishSweepJob(ctx context.Context, arg FinishSweepJobParams) error {
	_, err := q.db.ExecContext(ctx, finishSweepJob,
		arg.Status,
		arg.FinishedAt,
		arg.RunDurationMs,
		arg.ID,
	)
	return err
}

const getComparison = `-- name: GetComparison :one
SELECT id, name, description, simulation_ids, metric, created_at, result_json FROM comparisons WHERE id = ? LIMIT 1
`

func (q *Queries) GetComparison(ctx context.Context, id int64) (Comparison, error) {
	row := q.db.QueryRowContext(ctx, getComparison, id)
	var i Comparison
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SimulationIds,
		&i.Metric,
		&i.CreatedAt,
		&i.ResultJson,
	)
	return i, err
}

const getComparisonMetrics = `-- name: GetComparisonMetrics :many
SELECT id, comparison_id, simulation_id, metric_name, metric_value, rank, percentile FROM comparison_metrics
WHERE comparison_id = ?
ORDER BY rank ASC
`

func (q *Queries) GetComparisonMetrics(ctx context.Context, comparisonID int64) ([]ComparisonMetric, error) {
	rows, err := q.db.QueryContext(ctx, getComparisonMetrics, comparisonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComparisonMetric
	for rows.Next() {
		var i ComparisonMetric
		if err := rows.Scan(
			&i.ID,
			&i.ComparisonID,
			&i.SimulationID,
			&i.MetricName,
			&i.MetricValue,
			&i.Rank,
			&i.Percentile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSweepJob = `-- name: GetSweepJob :one
SELECT id, name, description, sweep_config_json, base_contest_range, status, total_combinations, completed_simulations, failed_simulations, created_at, started_at, finished_at, run_duration_ms, created_by FROM sweep_jobs WHERE id = ? LIMIT 1
`

func (q *Queries) GetSweepJob(ctx context.Context, id int64) (SweepJob, error) {
	row := q.db.QueryRowContext(ctx, getSweepJob, id)
	var i SweepJob
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SweepConfigJson,
		&i.BaseContestRange,
		&i.Status,
		&i.TotalCombinations,
		&i.CompletedSimulations,
		&i.FailedSimulations,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.RunDurationMs,
		&i.CreatedBy,
	)
	return i, err
}

const getSweepSimulationDetails = `-- name: GetSweepSimulationDetails :many
SELECT
    ss.id, ss.sweep_job_id, ss.simulation_id, ss.variation_index, ss.variation_params,
    s.status,
    s.summary_json,
    s.run_duration_ms
FROM sweep_simulations ss
JOIN simulations s ON ss.simulation_id = s.id
WHERE ss.sweep_job_id = ?
ORDER BY ss.variation_index ASC
`

type GetSweepSimulationDetailsRow struct {
	ID              int64          `json:"id"`
	SweepJobID      int64          `json:"sweep_job_id"`
	SimulationID    int64          `json:"simulation_id"`
	VariationIndex  int64          `json:"variation_index"`
	VariationParams string         `json:"variation_params"`
	Status          string         `json:"status"`
	SummaryJson     sql.NullString `json:"summary_json"`
	RunDurationMs   sql.NullInt64  `json:"run_duration_ms"`
}

func (q *Queries) GetSweepSimulationDetails(ctx context.Context, sweepJobID int64) ([]GetSweepSimulationDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, getSweepSimulationDetails, sweepJobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSweepSimulationDetailsRow
	for rows.Next() {
		var i GetSweepSimulationDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.SweepJobID,
			&i.SimulationID,
			&i.VariationIndex,
			&i.VariationParams,
			&i.Status,
			&i.SummaryJson,
			&i.RunDurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSweepSimulations = `-- name: GetSweepSimulations :many
SELECT id, sweep_job_id, simulation_id, variation_index, variation_params FROM sweep_simulations
WHERE sweep_job_id = ?
ORDER BY variation_index ASC
`

func (q *Queries) GetSweepSimulations(ctx context.Context, sweepJobID int64) ([]SweepSimulation, error) {
	rows, err := q.db.QueryContext(ctx, getSweepSimulations, sweepJobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SweepSimulation
	for rows.Next() {
		var i SweepSimulation
		if err := rows.Scan(
			&i.ID,
			&i.SweepJobID,
			&i.SimulationID,
			&i.VariationIndex,
			&i.VariationParams,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertComparisonMetric = `-- name: InsertComparisonMetric :exec
INSERT INTO comparison_metrics (
    comparison_id, simulation_id, metric_name, metric_value, rank, percentile
) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertComparisonMetricParams struct {
	ComparisonID int64           `json:"comparison_id"`
	SimulationID int64           `json:"simulation_id"`
	MetricName   string          `json:"metric_name"`
	MetricValue  float64         `json:"metric_value"`
	Rank         sql.NullInt64   `json:"rank"`
	Percentile   sql.NullFloat64 `json:"percentile"`
}

func (q *Queries) InsertComparisonMetric(ctx context.Context, arg InsertComparisonMetricParams) error {
	_, err := q.db.ExecContext(ctx, insertComparisonMetric,
		arg.ComparisonID,
		arg.SimulationID,
		arg.MetricName,
		arg.MetricValue,
		arg.Rank,
		arg.Percentile,
	)
	return err
}

const listSweepJobs = `-- name: ListSweepJobs :many
SELECT id, name, description, sweep_config_json, base_contest_range, status, total_combinations, completed_simulations, failed_simulations, created_at, started_at, finished_at, run_duration_ms, created_by FROM sweep_jobs
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListSweepJobsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListSweepJobs(ctx context.Context, arg ListSweepJobsParams) ([]SweepJob, error) {
	rows, err := q.db.QueryContext(ctx, listSweepJobs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SweepJob
	for rows.Next() {
		var i SweepJob
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.SweepConfigJson,
			&i.BaseContestRange,
			&i.Status,
			&i.TotalCombinations,
			&i.CompletedSimulations,
			&i.FailedSimulations,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.RunDurationMs,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComparisonResult = `-- name: UpdateComparisonResult :exec
UPDATE comparisons
SET result_json = ?
WHERE id = ?
`

type UpdateComparisonResultParams struct {
	ResultJson sql.NullString `json:"result_json"`
	ID         int64          `json:"id"`
}

func (q *Queries) UpdateComparisonResult(ctx context.Context, arg UpdateComparisonResultParams) error {
	_, err := q.db.ExecContext(ctx, updateComparisonResult, arg.ResultJson, arg.ID)
	return err
}

const updateSweepJobProgress = `-- name: UpdateSweepJobProgress :exec
UPDATE sweep_jobs
SET completed_simulations = ?,
    failed_simulations = ?,
    status = ?
WHERE id = ?
`

type UpdateSweepJobProgressParams struct {
	CompletedSimulations sql.NullInt64 `json:"completed_simulations"`
	FailedSimulations    sql.NullInt64 `json:"failed_simulations"`
	Status               string        `json:"status"`
	ID                   int64         `json:"id"`
}

func (q *Queries) UpdateSweepJobProgress(ctx context.Context, arg UpdateSweepJobProgressParams) error {
	_, err := q.db.ExecContext(ctx, updateSweepJobProgress,
		arg.CompletedSimulations,
		arg.FailedSimulations,
		arg.Status,
		arg.ID,
	)
	return err
}
