// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comparisons.sql

package comparisons

import (
	"context"
	"database/sql"
)

const createComparison = `-- name: CreateComparison :one
INSERT INTO comparisons (
    name, description, simulation_ids, metric
) VALUES (?, ?, ?, ?)
RETURNING id, name, description, simulation_ids, metric, created_at, result_json
`

type CreateComparisonParams struct {
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	SimulationIds string         `json:"simulation_ids"`
	Metric        string         `json:"metric"`
}

func (q *Queries) CreateComparison(ctx context.Context, arg CreateComparisonParams) (Comparison, error) {
	row := q.db.QueryRowContext(ctx, createComparison,
		arg.Name,
		arg.Description,
		arg.SimulationIds,
		arg.Metric,
	)
	var i Comparison
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SimulationIds,
		&i.Metric,
		&i.CreatedAt,
		&i.ResultJson,
	)
	return i, err
}

const deleteComparison = `-- name: DeleteComparison :exec
DELETE FROM comparisons WHERE id = ?
`

func (q *Queries) DeleteComparison(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteComparison, id)
	return err
}

const getComparison = `-- name: GetComparison :one
SELECT id, name, description, simulation_ids, metric, created_at, result_json FROM comparisons WHERE id = ? LIMIT 1
`

func (q *Queries) GetComparison(ctx context.Context, id int64) (Comparison, error) {
	row := q.db.QueryRowContext(ctx, getComparison, id)
	var i Comparison
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SimulationIds,
		&i.Metric,
		&i.CreatedAt,
		&i.ResultJson,
	)
	return i, err
}

const getComparisonMetrics = `-- name: GetComparisonMetrics :many
SELECT id, comparison_id, simulation_id, metric_name, metric_value, rank, percentile FROM comparison_metrics
WHERE comparison_id = ?
ORDER BY rank ASC
`

func (q *Queries) GetComparisonMetrics(ctx context.Context, comparisonID int64) ([]ComparisonMetric, error) {
	rows, err := q.db.QueryContext(ctx, getComparisonMetrics, comparisonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComparisonMetric
	for rows.Next() {
		var i ComparisonMetric
		if err := rows.Scan(
			&i.ID,
			&i.ComparisonID,
			&i.SimulationID,
			&i.MetricName,
			&i.MetricValue,
			&i.Rank,
			&i.Percentile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getComparisonMetricsBySimulation = `-- name: GetComparisonMetricsBySimulation :many
SELECT id, comparison_id, simulation_id, metric_name, metric_value, rank, percentile FROM comparison_metrics
WHERE simulation_id = ?
ORDER BY comparison_id ASC
`

func (q *Queries) GetComparisonMetricsBySimulation(ctx context.Context, simulationID int64) ([]ComparisonMetric, error) {
	rows, err := q.db.QueryContext(ctx, getComparisonMetricsBySimulation, simulationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComparisonMetric
	for rows.Next() {
		var i ComparisonMetric
		if err := rows.Scan(
			&i.ID,
			&i.ComparisonID,
			&i.SimulationID,
			&i.MetricName,
			&i.MetricValue,
			&i.Rank,
			&i.Percentile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertComparisonMetric = `-- name: InsertComparisonMetric :exec
INSERT INTO comparison_metrics (
    comparison_id, simulation_id, metric_name, metric_value, rank, percentile
) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertComparisonMetricParams struct {
	ComparisonID int64           `json:"comparison_id"`
	SimulationID int64           `json:"simulation_id"`
	MetricName   string          `json:"metric_name"`
	MetricValue  float64         `json:"metric_value"`
	Rank         sql.NullInt64   `json:"rank"`
	Percentile   sql.NullFloat64 `json:"percentile"`
}

func (q *Queries) InsertComparisonMetric(ctx context.Context, arg InsertComparisonMetricParams) error {
	_, err := q.db.ExecContext(ctx, insertComparisonMetric,
		arg.ComparisonID,
		arg.SimulationID,
		arg.MetricName,
		arg.MetricValue,
		arg.Rank,
		arg.Percentile,
	)
	return err
}

const listComparisons = `-- name: ListComparisons :many
SELECT id, name, description, simulation_ids, metric, created_at, result_json FROM comparisons
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListComparisonsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListComparisons(ctx context.Context, arg ListComparisonsParams) ([]Comparison, error) {
	rows, err := q.db.QueryContext(ctx, listComparisons, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comparison
	for rows.Next() {
		var i Comparison
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.SimulationIds,
			&i.Metric,
			&i.CreatedAt,
			&i.ResultJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComparisonResult = `-- name: UpdateComparisonResult :exec
UPDATE comparisons
SET result_json = ?
WHERE id = ?
`

type UpdateComparisonResultParams struct {
	ResultJson sql.NullString `json:"result_json"`
	ID         int64          `json:"id"`
}

func (q *Queries) UpdateComparisonResult(ctx context.Context, arg UpdateComparisonResultParams) error {
	_, err := q.db.ExecContext(ctx, updateComparisonResult, arg.ResultJson, arg.ID)
	return err
}
