// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package comparisons

import (
	"context"
)

type Querier interface {
	CreateComparison(ctx context.Context, arg CreateComparisonParams) (Comparison, error)
	DeleteComparison(ctx context.Context, id int64) error
	GetComparison(ctx context.Context, id int64) (Comparison, error)
	GetComparisonMetrics(ctx context.Context, comparisonID int64) ([]ComparisonMetric, error)
	GetComparisonMetricsBySimulation(ctx context.Context, simulationID int64) ([]ComparisonMetric, error)
	InsertComparisonMetric(ctx context.Context, arg InsertComparisonMetricParams) error
	ListComparisons(ctx context.Context, arg ListComparisonsParams) ([]Comparison, error)
	UpdateComparisonResult(ctx context.Context, arg UpdateComparisonResultParams) error
}

var _ Querier = (*Queries)(nil)
