// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package simulations

import (
	"context"
)

type Querier interface {
	CancelSimulation(ctx context.Context, arg CancelSimulationParams) error
	ClaimPendingSimulation(ctx context.Context, arg ClaimPendingSimulationParams) (Simulation, error)
	CompleteSimulation(ctx context.Context, arg CompleteSimulationParams) error
	CountSimulationsByStatus(ctx context.Context, status string) (int64, error)
	CreateSimulation(ctx context.Context, arg CreateSimulationParams) (Simulation, error)
	FailSimulation(ctx context.Context, arg FailSimulationParams) error
	GetContestResults(ctx context.Context, arg GetContestResultsParams) ([]SimulationContestResult, error)
	GetContestResultsByMinHits(ctx context.Context, arg GetContestResultsByMinHitsParams) ([]SimulationContestResult, error)
	GetSimulation(ctx context.Context, id int64) (Simulation, error)
	InsertContestResult(ctx context.Context, arg InsertContestResultParams) error
	ListSimulations(ctx context.Context, arg ListSimulationsParams) ([]Simulation, error)
	ListSimulationsByStatus(ctx context.Context, arg ListSimulationsByStatusParams) ([]Simulation, error)
	UpdateSimulationStatus(ctx context.Context, arg UpdateSimulationStatusParams) error
}

var _ Querier = (*Queries)(nil)
