// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: simulations.sql

package simulations

import (
	"context"
)

const getSimulation = `-- name: GetSimulation :one
SELECT id, name FROM simulations
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetSimulation(ctx context.Context, id int64) (Simulation, error) {
	row := q.db.QueryRowContext(ctx, getSimulation, id)
	var i Simulation
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listSimulations = `-- name: ListSimulations :many
SELECT id, name FROM simulations
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListSimulationsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListSimulations(ctx context.Context, arg ListSimulationsParams) ([]Simulation, error) {
	rows, err := q.db.QueryContext(ctx, listSimulations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Simulation
	for rows.Next() {
		var i Simulation
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
