// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/engine.go

// Package services is a generated GoMock package.
package services

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockEngineServicer is a mock of EngineServicer interface.
type MockEngineServicer struct {
	ctrl     *gomock.Controller
	recorder *MockEngineServicerMockRecorder
}

// MockEngineServicerMockRecorder is the mock recorder for MockEngineServicer.
type MockEngineServicerMockRecorder struct {
	mock *MockEngineServicer
}

// NewMockEngineServicer creates a new mock instance.
func NewMockEngineServicer(ctrl *gomock.Controller) *MockEngineServicer {
	mock := &MockEngineServicer{ctrl: ctrl}
	mock.recorder = &MockEngineServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEngineServicer) EXPECT() *MockEngineServicerMockRecorder {
	return m.recorder
}

// RunSimulation mocks base method.
func (m *MockEngineServicer) RunSimulation(ctx context.Context, cfg SimulationConfig) (*SimulationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunSimulation", ctx, cfg)
	ret0, _ := ret[0].(*SimulationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunSimulation indicates an expected call of RunSimulation.
func (mr *MockEngineServicerMockRecorder) RunSimulation(ctx, cfg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunSimulation", reflect.TypeOf((*MockEngineServicer)(nil).RunSimulation), ctx, cfg)
}
