// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/simulation.go

// Package services is a generated GoMock package.
package services

import (
	context "context"
	reflect "reflect"

	simulations "github.com/garnizeh/luckyfive/internal/store/simulations"
	gomock "github.com/golang/mock/gomock"
)

// MockSimulationServicer is a mock of SimulationServicer interface.
type MockSimulationServicer struct {
	ctrl     *gomock.Controller
	recorder *MockSimulationServicerMockRecorder
}

// MockSimulationServicerMockRecorder is the mock recorder for MockSimulationServicer.
type MockSimulationServicerMockRecorder struct {
	mock *MockSimulationServicer
}

// NewMockSimulationServicer creates a new mock instance.
func NewMockSimulationServicer(ctrl *gomock.Controller) *MockSimulationServicer {
	mock := &MockSimulationServicer{ctrl: ctrl}
	mock.recorder = &MockSimulationServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSimulationServicer) EXPECT() *MockSimulationServicerMockRecorder {
	return m.recorder
}

// CancelSimulation mocks base method.
func (m *MockSimulationServicer) CancelSimulation(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelSimulation", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelSimulation indicates an expected call of CancelSimulation.
func (mr *MockSimulationServicerMockRecorder) CancelSimulation(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelSimulation", reflect.TypeOf((*MockSimulationServicer)(nil).CancelSimulation), ctx, id)
}

// CreateSimulation mocks base method.
func (m *MockSimulationServicer) CreateSimulation(ctx context.Context, req CreateSimulationRequest) (*simulations.Simulation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSimulation", ctx, req)
	ret0, _ := ret[0].(*simulations.Simulation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSimulation indicates an expected call of CreateSimulation.
func (mr *MockSimulationServicerMockRecorder) CreateSimulation(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSimulation", reflect.TypeOf((*MockSimulationServicer)(nil).CreateSimulation), ctx, req)
}

// ExecuteSimulation mocks base method.
func (m *MockSimulationServicer) ExecuteSimulation(ctx context.Context, simID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteSimulation", ctx, simID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteSimulation indicates an expected call of ExecuteSimulation.
func (mr *MockSimulationServicerMockRecorder) ExecuteSimulation(ctx, simID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteSimulation", reflect.TypeOf((*MockSimulationServicer)(nil).ExecuteSimulation), ctx, simID)
}

// GetContestResults mocks base method.
func (m *MockSimulationServicer) GetContestResults(ctx context.Context, simulationID int64, limit, offset int) ([]simulations.SimulationContestResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContestResults", ctx, simulationID, limit, offset)
	ret0, _ := ret[0].([]simulations.SimulationContestResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContestResults indicates an expected call of GetContestResults.
func (mr *MockSimulationServicerMockRecorder) GetContestResults(ctx, simulationID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContestResults", reflect.TypeOf((*MockSimulationServicer)(nil).GetContestResults), ctx, simulationID, limit, offset)
}

// GetSimulation mocks base method.
func (m *MockSimulationServicer) GetSimulation(ctx context.Context, id int64) (*simulations.Simulation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSimulation", ctx, id)
	ret0, _ := ret[0].(*simulations.Simulation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSimulation indicates an expected call of GetSimulation.
func (mr *MockSimulationServicerMockRecorder) GetSimulation(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSimulation", reflect.TypeOf((*MockSimulationServicer)(nil).GetSimulation), ctx, id)
}

// ListSimulations mocks base method.
func (m *MockSimulationServicer) ListSimulations(ctx context.Context, limit, offset int) ([]simulations.Simulation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSimulations", ctx, limit, offset)
	ret0, _ := ret[0].([]simulations.Simulation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSimulations indicates an expected call of ListSimulations.
func (mr *MockSimulationServicerMockRecorder) ListSimulations(ctx, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSimulations", reflect.TypeOf((*MockSimulationServicer)(nil).ListSimulations), ctx, limit, offset)
}
