package handlers

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/go-chi/chi/v5/middleware"

	"github.com/garnizeh/luckyfive/internal/models"
)

func TestWriteJSON(t *testing.T) {
	// Test data
	testData := map[string]interface{}{
		"message": "success",
		"data": map[string]string{
			"key": "value",
		},
	}

	// Create response recorder
	w := httptest.NewRecorder()

	// Call WriteJSON
	WriteJSON(w, http.StatusOK, testData)

	// Check status code
	if w.Code != http.StatusOK {
		t.Errorf("Expected status code %d, got %d", http.StatusOK, w.Code)
	}

	// Check content type
	contentType := w.Header().Get("Content-Type")
	if contentType != "application/json" {
		t.Errorf("Expected Content-Type 'application/json', got '%s'", contentType)
	}

	// Check response body
	var response map[string]interface{}
	if err := json.NewDecoder(w.Body).Decode(&response); err != nil {
		t.Fatalf("Failed to decode response JSON: %v", err)
	}

	// Verify response content
	if response["message"] != "success" {
		t.Errorf("Expected message 'success', got '%v'", response["message"])
	}

	data, ok := response["data"].(map[string]interface{})
	if !ok {
		t.Fatal("Expected 'data' to be a map")
	}

	if data["key"] != "value" {
		t.Errorf("Expected data.key 'value', got '%v'", data["key"])
	}
}

func TestWriteError_WithoutRequestID(t *testing.T) {
	// Create error
	apiErr := models.NewAPIError("test_error", "This is a test error")

	// Create request without request ID
	req := httptest.NewRequest(http.MethodGet, "/test", nil)
	w := httptest.NewRecorder()

	// Call WriteError
	WriteError(w, req, *apiErr)

	// Check status code (should be InternalServerError for unknown error code)
	if w.Code != http.StatusInternalServerError {
		t.Errorf("Expected status code %d, got %d", http.StatusInternalServerError, w.Code)
	}

	// Check content type
	contentType := w.Header().Get("Content-Type")
	if contentType != "application/json" {
		t.Errorf("Expected Content-Type 'application/json', got '%s'", contentType)
	}

	// Check response body
	var response models.APIError
	if err := json.NewDecoder(w.Body).Decode(&response); err != nil {
		t.Fatalf("Failed to decode response JSON: %v", err)
	}

	// Verify response content
	if response.Code != "test_error" {
		t.Errorf("Expected code 'test_error', got '%s'", response.Code)
	}

	if response.Message != "This is a test error" {
		t.Errorf("Expected message 'This is a test error', got '%s'", response.Message)
	}

	if response.RequestID != "" {
		t.Errorf("Expected empty request ID, got '%s'", response.RequestID)
	}
}

func TestWriteError_WithRequestID(t *testing.T) {
	// Create error
	apiErr := models.NewAPIError("not_found", "Resource not found")

	// Create request and apply RequestID middleware
	req := httptest.NewRequest(http.MethodGet, "/test", nil)

	// Create a test handler that applies RequestID middleware
	handler := middleware.RequestID(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		WriteError(w, r, *apiErr)
	}))

	w := httptest.NewRecorder()
	handler.ServeHTTP(w, req)

	// Check status code (should be NotFound for "not_found" error)
	if w.Code != http.StatusNotFound {
		t.Errorf("Expected status code %d, got %d", http.StatusNotFound, w.Code)
	}

	// Check response body
	var response models.APIError
	if err := json.NewDecoder(w.Body).Decode(&response); err != nil {
		t.Fatalf("Failed to decode response JSON: %v", err)
	}

	// Verify request ID is included (should be generated by middleware)
	if response.RequestID == "" {
		t.Error("Expected request ID to be present, but it was empty")
	}
}

func TestWriteError_WithDetails(t *testing.T) {
	// Create error with details
	apiErr := models.NewAPIError("validation_error", "Invalid input").
		WithDetails(map[string]interface{}{
			"field":  "username",
			"reason": "required",
		})

	// Create request
	req := httptest.NewRequest(http.MethodPost, "/test", nil)
	w := httptest.NewRecorder()

	// Call WriteError
	WriteError(w, req, *apiErr)

	// Check status code
	if w.Code != http.StatusBadRequest {
		t.Errorf("Expected status code %d, got %d", http.StatusBadRequest, w.Code)
	}

	// Check response body
	var response models.APIError
	if err := json.NewDecoder(w.Body).Decode(&response); err != nil {
		t.Fatalf("Failed to decode response JSON: %v", err)
	}

	// Verify details are included
	if response.Details == nil {
		t.Fatal("Expected details to be present")
	}

	if response.Details["field"] != "username" {
		t.Errorf("Expected details.field 'username', got '%v'", response.Details["field"])
	}

	if response.Details["reason"] != "required" {
		t.Errorf("Expected details.reason 'required', got '%v'", response.Details["reason"])
	}
}

func TestWriteValidationError(t *testing.T) {
	// Create validation error
	fieldErrors := map[string]string{
		"username": "required",
		"email":    "invalid format",
	}
	valErr := models.NewValidationError("Validation failed", fieldErrors)

	// Create request and apply RequestID middleware
	req := httptest.NewRequest(http.MethodPost, "/test", nil)

	// Create a test handler that applies RequestID middleware
	handler := middleware.RequestID(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		WriteValidationError(w, r, *valErr)
	}))

	w := httptest.NewRecorder()
	handler.ServeHTTP(w, req)

	// Check status code
	if w.Code != http.StatusBadRequest {
		t.Errorf("Expected status code %d, got %d", http.StatusBadRequest, w.Code)
	}

	// Check content type
	contentType := w.Header().Get("Content-Type")
	if contentType != "application/json" {
		t.Errorf("Expected Content-Type 'application/json', got '%s'", contentType)
	}

	// Check response body
	var response models.ValidationError
	if err := json.NewDecoder(w.Body).Decode(&response); err != nil {
		t.Fatalf("Failed to decode response JSON: %v", err)
	}

	// Verify response content
	if response.Code != "validation_error" {
		t.Errorf("Expected code 'validation_error', got '%s'", response.Code)
	}

	if response.Message != "Validation failed" {
		t.Errorf("Expected message 'Validation failed', got '%s'", response.Message)
	}

	// Verify request ID is included
	if response.RequestID == "" {
		t.Error("Expected request ID to be present, but it was empty")
	}

	// Verify field errors
	if response.FieldErrors == nil {
		t.Fatal("Expected field errors to be present")
	}

	if response.FieldErrors["username"] != "required" {
		t.Errorf("Expected field error for username 'required', got '%s'", response.FieldErrors["username"])
	}

	if response.FieldErrors["email"] != "invalid format" {
		t.Errorf("Expected field error for email 'invalid format', got '%s'", response.FieldErrors["email"])
	}
}

func TestWriteValidationError_WithoutRequestID(t *testing.T) {
	// Create validation error
	fieldErrors := map[string]string{
		"password": "too short",
	}
	valErr := models.NewValidationError("Password validation failed", fieldErrors)

	// Create request without request ID
	req := httptest.NewRequest(http.MethodPost, "/test", nil)
	w := httptest.NewRecorder()

	// Call WriteValidationError
	WriteValidationError(w, req, *valErr)

	// Check response body
	var response models.ValidationError
	if err := json.NewDecoder(w.Body).Decode(&response); err != nil {
		t.Fatalf("Failed to decode response JSON: %v", err)
	}

	// Verify request ID is empty
	if response.RequestID != "" {
		t.Errorf("Expected empty request ID, got '%s'", response.RequestID)
	}
}
