// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: configs.sql

package configs

import (
	"context"
	"database/sql"
)

const deleteConfig = `-- name: DeleteConfig :exec
DELETE FROM configs WHERE id = ?
`

func (q *Queries) DeleteConfig(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteConfig, id)
	return err
}

const getConfig = `-- name: GetConfig :one

SELECT id, name, description, recipe_json, tags, is_default, mode, created_at, updated_at, created_by, times_used, last_used_at FROM configs
WHERE id = ?
LIMIT 1
`

// schema: migrations/003_create_configs.sql
func (q *Queries) GetConfig(ctx context.Context, id int64) (Config, error) {
	row := q.db.QueryRowContext(ctx, getConfig, id)
	var i Config
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.RecipeJson,
		&i.Tags,
		&i.IsDefault,
		&i.Mode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.TimesUsed,
		&i.LastUsedAt,
	)
	return i, err
}

const getConfigByName = `-- name: GetConfigByName :one
SELECT id, name, description, recipe_json, tags, is_default, mode, created_at, updated_at, created_by, times_used, last_used_at FROM configs
WHERE name = ?
LIMIT 1
`

func (q *Queries) GetConfigByName(ctx context.Context, name string) (Config, error) {
	row := q.db.QueryRowContext(ctx, getConfigByName, name)
	var i Config
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.RecipeJson,
		&i.Tags,
		&i.IsDefault,
		&i.Mode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.TimesUsed,
		&i.LastUsedAt,
	)
	return i, err
}

const getConfigPresetByName = `-- name: GetConfigPresetByName :one
SELECT id, name, display_name, description, recipe_json, risk_level, is_active, sort_order FROM config_presets
WHERE name = ? AND is_active = 1
LIMIT 1
`

func (q *Queries) GetConfigPresetByName(ctx context.Context, name string) (ConfigPreset, error) {
	row := q.db.QueryRowContext(ctx, getConfigPresetByName, name)
	var i ConfigPreset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.RecipeJson,
		&i.RiskLevel,
		&i.IsActive,
		&i.SortOrder,
	)
	return i, err
}

const getConfigPresets = `-- name: GetConfigPresets :many
SELECT id, name, display_name, description, recipe_json, risk_level, is_active, sort_order FROM config_presets
WHERE is_active = 1
ORDER BY sort_order ASC
`

func (q *Queries) GetConfigPresets(ctx context.Context) ([]ConfigPreset, error) {
	rows, err := q.db.QueryContext(ctx, getConfigPresets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConfigPreset
	for rows.Next() {
		var i ConfigPreset
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.RecipeJson,
			&i.RiskLevel,
			&i.IsActive,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDefaultConfigForMode = `-- name: GetDefaultConfigForMode :one
SELECT id, name, description, recipe_json, tags, is_default, mode, created_at, updated_at, created_by, times_used, last_used_at FROM configs
WHERE mode = ? AND is_default = 1
LIMIT 1
`

func (q *Queries) GetDefaultConfigForMode(ctx context.Context, mode string) (Config, error) {
	row := q.db.QueryRowContext(ctx, getDefaultConfigForMode, mode)
	var i Config
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.RecipeJson,
		&i.Tags,
		&i.IsDefault,
		&i.Mode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.TimesUsed,
		&i.LastUsedAt,
	)
	return i, err
}

const insertConfig = `-- name: InsertConfig :one
INSERT INTO configs (name, description, recipe_json, tags, mode, created_by)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, name, description, recipe_json, tags, is_default, mode, created_at, updated_at, created_by, times_used, last_used_at
`

type InsertConfigParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	RecipeJson  string         `json:"recipe_json"`
	Tags        sql.NullString `json:"tags"`
	Mode        string         `json:"mode"`
	CreatedBy   sql.NullString `json:"created_by"`
}

func (q *Queries) InsertConfig(ctx context.Context, arg InsertConfigParams) (Config, error) {
	row := q.db.QueryRowContext(ctx, insertConfig,
		arg.Name,
		arg.Description,
		arg.RecipeJson,
		arg.Tags,
		arg.Mode,
		arg.CreatedBy,
	)
	var i Config
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.RecipeJson,
		&i.Tags,
		&i.IsDefault,
		&i.Mode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.TimesUsed,
		&i.LastUsedAt,
	)
	return i, err
}

const listConfigs = `-- name: ListConfigs :many
SELECT id, name, description, recipe_json, tags, is_default, mode, created_at, updated_at, created_by, times_used, last_used_at FROM configs
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListConfigsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListConfigs(ctx context.Context, arg ListConfigsParams) ([]Config, error) {
	rows, err := q.db.QueryContext(ctx, listConfigs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Config
	for rows.Next() {
		var i Config
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.RecipeJson,
			&i.Tags,
			&i.IsDefault,
			&i.Mode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.TimesUsed,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConfigsByMode = `-- name: ListConfigsByMode :many
SELECT id, name, description, recipe_json, tags, is_default, mode, created_at, updated_at, created_by, times_used, last_used_at FROM configs
WHERE mode = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListConfigsByModeParams struct {
	Mode   string `json:"mode"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListConfigsByMode(ctx context.Context, arg ListConfigsByModeParams) ([]Config, error) {
	rows, err := q.db.QueryContext(ctx, listConfigsByMode, arg.Mode, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Config
	for rows.Next() {
		var i Config
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.RecipeJson,
			&i.Tags,
			&i.IsDefault,
			&i.Mode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.TimesUsed,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setConfigAsDefault = `-- name: SetConfigAsDefault :exec
UPDATE configs SET is_default = CASE WHEN configs.id = ? THEN 1 ELSE 0 END
WHERE mode = (SELECT c.mode FROM configs c WHERE c.id = ?)
`

type SetConfigAsDefaultParams struct {
	ID   int64 `json:"id"`
	ID_2 int64 `json:"id_2"`
}

func (q *Queries) SetConfigAsDefault(ctx context.Context, arg SetConfigAsDefaultParams) error {
	_, err := q.db.ExecContext(ctx, setConfigAsDefault, arg.ID, arg.ID_2)
	return err
}

const updateConfig = `-- name: UpdateConfig :exec
UPDATE configs SET
  description = ?,
  recipe_json = ?,
  tags = ?,
  updated_at = CURRENT_TIMESTAMP,
  last_used_at = CURRENT_TIMESTAMP,
  times_used = times_used + 1
WHERE id = ?
`

type UpdateConfigParams struct {
	Description sql.NullString `json:"description"`
	RecipeJson  string         `json:"recipe_json"`
	Tags        sql.NullString `json:"tags"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateConfig(ctx context.Context, arg UpdateConfigParams) error {
	_, err := q.db.ExecContext(ctx, updateConfig,
		arg.Description,
		arg.RecipeJson,
		arg.Tags,
		arg.ID,
	)
	return err
}
