// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package configs

import (
	"database/sql"
)

type Config struct {
	ID          int64          `json:"id"`
	Key         string         `json:"key"`
	Value       sql.NullString `json:"value"`
	Description sql.NullString `json:"description"`
	UpdatedAt   string         `json:"updated_at"`
}

type ConfigPreset struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	Mode      string `json:"mode"`
	Settings  string `json:"settings"`
	IsDefault int64  `json:"is_default"`
	CreatedAt string `json:"created_at"`
}
