// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package configs

import (
	"database/sql"
)

type Config struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	RecipeJson  string         `json:"recipe_json"`
	Tags        sql.NullString `json:"tags"`
	IsDefault   sql.NullInt64  `json:"is_default"`
	Mode        string         `json:"mode"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
	CreatedBy   sql.NullString `json:"created_by"`
	TimesUsed   sql.NullInt64  `json:"times_used"`
	LastUsedAt  sql.NullString `json:"last_used_at"`
}

type ConfigPreset struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	DisplayName string         `json:"display_name"`
	Description sql.NullString `json:"description"`
	RecipeJson  string         `json:"recipe_json"`
	RiskLevel   sql.NullString `json:"risk_level"`
	IsActive    sql.NullInt64  `json:"is_active"`
	SortOrder   sql.NullInt64  `json:"sort_order"`
}
