// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package configs

import (
	"database/sql"
)

type Config struct {
	ID    int64          `json:"id"`
	Key   string         `json:"key"`
	Value sql.NullString `json:"value"`
}
