// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package configs

import (
	"context"
)

type Querier interface {
	GetConfig(ctx context.Context, id int64) (Config, error)
	ListConfigs(ctx context.Context, arg ListConfigsParams) ([]Config, error)
}

var _ Querier = (*Queries)(nil)
