// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package configs

import (
	"context"
)

type Querier interface {
	CreateConfig(ctx context.Context, arg CreateConfigParams) (Config, error)
	DeleteConfig(ctx context.Context, id int64) error
	GetConfig(ctx context.Context, id int64) (Config, error)
	GetConfigByName(ctx context.Context, name string) (Config, error)
	GetDefaultConfig(ctx context.Context, mode string) (Config, error)
	GetPreset(ctx context.Context, name string) (ConfigPreset, error)
	IncrementConfigUsage(ctx context.Context, id int64) error
	ListConfigs(ctx context.Context, arg ListConfigsParams) ([]Config, error)
	ListConfigsByMode(ctx context.Context, arg ListConfigsByModeParams) ([]Config, error)
	ListPresets(ctx context.Context) ([]ConfigPreset, error)
	SetDefaultConfig(ctx context.Context, arg SetDefaultConfigParams) error
	UpdateConfig(ctx context.Context, arg UpdateConfigParams) error
}

var _ Querier = (*Queries)(nil)
